"""empty message

Revision ID: 64bb94c4eac6
Revises: aabe25440349
Create Date: 2022-06-27 15:06:27.598375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64bb94c4eac6'
down_revision = 'aabe25440349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed_on')
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
