"""empty message

Revision ID: 8970d498d062
Revises: 
Create Date: 2022-06-24 15:54:46.358828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8970d498d062'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usertype', sa.Enum('admin', 'shopuser', 'customer', name='usertype'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'usertype')
    # ### end Alembic commands ###
